version: '3.8'

services:
  web:
    container_name: web
    image: web
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # пример ограничения памяти для контейнера
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 512M
    #     reservations:
    #       cpus: '1'
    #       memory: 256M
    volumes:
      - ./web/:/code
    expose:
      - 8000
    depends_on:
      - postgres
      - redis
    env_file:
      - ${ENV_FILE}
    networks:
      - alpha_network

  postgres:
    container_name: postgres
    image: postgres
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ${ENV_FILE}
    networks:
      - alpha_network

  redis:
    container_name: redis
    image: redis
    build:
      context: .
      dockerfile: docker/redis.Dockerfile
    volumes:
        - redis_data:/data
    ports:
      - 6379:6379
    env_file:
      - ${ENV_FILE}
    networks:
      - alpha_network

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - alpha_network

volumes:
  postgres_data:
  redis_data:

networks:
  alpha_network:
    driver: bridge
