version: '3.8'

services:
  web:
    container_name: web
    image: web
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./web/:/code
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - alpha_network

  db:
    container_name: db
    image: db
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env
    networks:
      - alpha_network

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - alpha_network

volumes:
  postgres_data:

networks:
  alpha_network:
    driver: bridge
