version: '3.8'

services:
  core_dj:
    container_name: core_dj
    image: core_dj
    build:
      context: .
      dockerfile: docker/core_dj.Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    # пример ограничения памяти для контейнера
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 512M
    #     reservations:
    #       cpus: '1'
    #       memory: 256M
    volumes:
      - ./apps/core_dj/:/code
    expose:
      - 8000
    depends_on:
      - postgres
    env_file:
      - ./apps/.env
    networks:
      - alpha_network

  postgres:
    container_name: postgres
    image: postgres
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./apps/.env
    networks:
      - alpha_network

  # redis:
  #   container_name: redis
  #   image: redis
  #   build:
  #     context: .
  #     dockerfile: docker/redis.Dockerfile
  #   volumes:
  #       - redis_data:/data
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - alpha_network

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - 1337:80
    depends_on:
      - core_dj
    networks:
      - alpha_network

volumes:
  postgres_data:
  # redis_data:

networks:
  alpha_network:
    driver: bridge
