version: '3.8'

services:
  auth:
    container_name: auth
    image: auth
    build:
      context: .
      dockerfile: docker/auth.Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    # пример ограничения памяти для контейнера
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M
    volumes:
      - ./apps/auth/:/code
    expose:
      - 8001
    depends_on:
      - db
    env_file:
      - ./apps/.env
    networks:
      - alpha_network

  web:
    container_name: web
    image: web
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./apps/web/:/code
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./apps/.env
    networks:
      - alpha_network

  db:
    container_name: db
    image: db
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./apps/.env
    networks:
      - alpha_network

  redis:
    container_name: redis
    image: redis
    build:
      context: .
      dockerfile: docker/redis.Dockerfile
    volumes:
        - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - alpha_network

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - alpha_network

volumes:
  postgres_data:
  redis_data:

networks:
  alpha_network:
    driver: bridge
